### ISSUE TITLE
A strange pink tint in the xyY scaling image.

### ISSUE THREAD

**Issue by gunjantomer** [evamy/learning_to_see#2]
After recent changes, the resulting image has increased luminance, but a strange pinkish tint covers the whole image. May be some mistake in the xyY color conversion.

**Comment by antiDigest** [comment]
Hi,

I did update the code files I had on my system. Please check. If the pinkish tint still persists, I'll push your pull request.

**Comment by gunjantomer** [comment]
When did you update them? I corrected the code and ran it last night. The tint was still there.

**Comment by antiDigest** [comment]
In the morning.
